# Generated by Django 2.2.1 on 2019-05-07 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LinkModel',
            fields=[
                ('long_url', models.CharField(max_length=10000)),
                ('checksum', models.CharField(primary_key=True, max_length=20)),
            ],
        ),
    ]
